# Helper Script to Import Data from Ubisense

Script to import data from Ubisense "all rawdata" download. Reads in data, checks for any inconsistencies in tag recordings and outputs a cleaned data set for analysis. This is anticipated for use in preparing data for integration with observed data and environmental analysis.

Reads in a csv file in the following format:

`Patient, Location, from, to  `

It then cleans the data to:
- split the location data in to x and y columns
- rename the `from` `to` columns to avoid keyword conlicts 
- deletes any rows that dont start with G or R
- look for any records where start to finish are over 24 hours (since these are probably not valid or stale tags) and removes all records for that tag id
- looks at each tag record and if any have a start and finish time that are more than an hour it deletes that individual entry (sometimes tag end times are a few hours after the end of a shift)
- for each patient we look for any journeys greater than 6 hours and delete them (assumes incorrect tag allocation)
- for each patient we look for any journeys less than 15 minutes and delete them 

Finally the output is saved to csv and has the format:

`Patient, Location, starttime,	endtime,	xlocation,	ylocation, step_length `

## Initialisation

Import dependencies, create helper function, initialise some variables including loading in data. Files to import are based on the Ubisense "all rawdata" downloads from the reports section of their application interface. These are stored locally in the project "Teams" folder Data>ubisense>rawdata_smartspaces and usually have a filename such as "phase2_all_20220130.csv".

In [32]:
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import numpy as np
import datetime as dt
import math
import seaborn as sns
import scipy.stats as sps
from scipy import stats

order_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
order_list_noweekend = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

pd.set_option('display.max_rows', 300) # specifies number of rows to show
pd.options.display.float_format = '{:40,.4f}'.format # specifies default number format to 4 decimal places
plt.style.use('ggplot') # specifies that graphs should use ggplot styling

phase = 'P1' # edit which Phase you are analysing - this is used in graph and file generation

df = pd.read_csv('{}_raw.csv'.format(phase))
df # check what column headings in file

      Patient      Location                  from                    to
0        Test  19.754,4.009  26/11/2021, 17:46:45  26/11/2021, 23:00:04
1        Test  19.953,4.284  26/11/2021, 17:46:23  26/11/2021, 17:46:45
2        Test  19.747,5.982  26/11/2021, 16:54:05  26/11/2021, 17:46:23
3        Test  21.609,6.115  26/11/2021, 16:53:54  26/11/2021, 16:54:05
4        Test   19.735,5.45  26/11/2021, 16:41:24  26/11/2021, 16:53:54
...       ...           ...                   ...                   ...
76647   fdsds   7.241,7.678  07/10/2021, 12:02:11  07/10/2021, 12:08:13
76648   fdsds  10.463,7.237  07/10/2021, 12:01:22  07/10/2021, 12:02:11
76649   fdsds   7.296,7.093  07/10/2021, 11:55:49  07/10/2021, 12:01:22
76650   fdsds  10.551,4.856  07/10/2021, 11:55:45  07/10/2021, 11:55:49
76651   fdsds   7.356,6.028  07/10/2021, 11:55:43  07/10/2021, 11:55:45

[76652 rows x 4 columns]

## Data Cleaning and Formatting

The section below is very similar if not the same across all three phases. Key differences are called out but this is where the data is formatted for analysis.

In [2]:
df = df.dropna() # remove any rows with null values
df[['xlocation', 'ylocation']] = df['Location'].str.split(',', expand = True) # create seperate columns for the x y values
df['from'] = pd.to_datetime(df['from'], dayfirst=True) # datetime in YYYY-MM-DD HH:MM:SS format
df['to'] = pd.to_datetime(df['to'], dayfirst=True)
df.rename(columns={"from": "starttime", "to": "endtime"}, inplace=True) # renaming from and to column headings (from is a keyword)
df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Patient,Location,starttime,endtime,xlocation,ylocation
0,Test,"19.754,4.009",2021-11-26 17:46:45,2021-11-26 23:00:04,19.754,4.009
1,Test,"19.953,4.284",2021-11-26 17:46:23,2021-11-26 17:46:45,19.953,4.284
2,Test,"19.747,5.982",2021-11-26 16:54:05,2021-11-26 17:46:23,19.747,5.982
3,Test,"21.609,6.115",2021-11-26 16:53:54,2021-11-26 16:54:05,21.609,6.115
4,Test,"19.735,5.45",2021-11-26 16:41:24,2021-11-26 16:53:54,19.735,5.45
...,...,...,...,...,...,...
76647,fdsds,"7.241,7.678",2021-10-07 12:02:11,2021-10-07 12:08:13,7.241,7.678
76648,fdsds,"10.463,7.237",2021-10-07 12:01:22,2021-10-07 12:02:11,10.463,7.237
76649,fdsds,"7.296,7.093",2021-10-07 11:55:49,2021-10-07 12:01:22,7.296,7.093
76650,fdsds,"10.551,4.856",2021-10-07 11:55:45,2021-10-07 11:55:49,10.551,4.856
76651,fdsds,"7.356,6.028",2021-10-07 11:55:43,2021-10-07 11:55:45,7.356,6.028

In [3]:
df[~df["Patient"].str.startswith(('G', 'R'))] # look for any records that dont (~) start with G or R

,Patient,Location,starttime,endtime,xlocation,ylocation
0,Test,"19.754,4.009",2021-11-26 17:46:45,2021-11-26 23:00:04,19.754,4.009
1,Test,"19.953,4.284",2021-11-26 17:46:23,2021-11-26 17:46:45,19.953,4.284
2,Test,"19.747,5.982",2021-11-26 16:54:05,2021-11-26 17:46:23,19.747,5.982
3,Test,"21.609,6.115",2021-11-26 16:53:54,2021-11-26 16:54:05,21.609,6.115
4,Test,"19.735,5.45",2021-11-26 16:41:24,2021-11-26 16:53:54,19.735,5.45
5,Test,"20.684,7.131",2021-11-26 16:41:11,2021-11-26 16:41:24,20.684,7.131
8,Test 2,"13.16,3.133",2021-11-23 17:08:47,2021-11-23 17:16:56,13.16,3.133
9,Test 2,"11.849,4.579",2021-11-23 17:08:05,2021-11-23 17:08:47,11.849,4.579
10,Test 2,"12.089,4.21",2021-11-23 17:07:52,2021-11-23 17:08:05,12.089,4.21
11,Test 2,"12.589,3.301",2021-11-23 17:07:36,2021-11-23 17:07:52,12.589,3.301
12,Test,"10.879,4.807",2021-11-23 17:06:02,2021-11-23 17:16:56,10.879,4.807
13,Test,"11.994,4.303",2021-11-23 17:05:47,2021-11-23 17:06:02,11.994,4.303
14,Test,"13.051,3.789",2021-11-23 17:05:20,2021-11-23 17:05:47,13.051,3.789
15,Test,"10.879,4.807",2021-11-23 17:04:54,2021-11-23 17:05:20,10.879,4.807
16,Test,"11.873,4.275",2021-11-23 17:04:49,2021-11-23 17:04:54,11.873,4.275
17,Test,"12.754,3.008",2021-11-23 17:04:42,2021-11-23 17:04:49,12.754,3.008
18,Test,"11.569,4.976",2021-11-23 17:03:43,2021-11-23 17:04:42,11.569,4.976
19,Test,"11.402,3.927",2021-11-23 17:03:38,2021-11-23 17:03:43,11.402,3.927
20,Test,"11.709,4.962",2021-11-23 16:34:06,2021-11-23 17:03:38,11.709,4.962
21,Test,"13.412,3.157",2021-11-23 16:33:40,2021-11-23 16:34:06,13.412,3.157
22,Test,"11.834,4.534",2021-11-23 16:30:59,2021-11-23 16:33:40,11.834,4.534
23,Test,"12.908,4.258",2021-11-23 16:30:47,2021-11-23 16:30:59,12.908,4.258
24,Test,"11.981,4.767",2021-11-23 16:09:53,2021-11-23 16:30:47,11.981,4.767
25,Test,"13.069,3.738",2021-11-23 16:09:45,2021-11-23 16:09:53,13.069,3.738
26,Test,"12.652,4.856",2021-11-23 15:58:01,2021-11-23 16:09:45,12.652,4.856
27,Test,"12.8,3.402",2021-11-23 15:56:08,2021-11-23 15:58:01,12.8,3.402
28,Test,"11.724,4.712",2021-11-23 15:54:31,2021-11-23 15:56:08,11.724,4.712
29,Test,"13.068,4.794",2021-11-23 15:19:34,2021-11-23 15:54:31,13.068,4.794
30,Test,"11.717,4.685",2021-11-23 15:19:26,2021-11-23 15:19:34,11.717,4.685
31,Test,"12.954,4.996",2021-11-23 15:18:47,2021-11-23 15:19:26,12.954,4.996
32,Test,"11.853,4.777",2021-11-23 15:18:26,2021-11-23 15:18:47,11.853,4.777
33,Test,"13.111,4.418",2021-11-23 15:17:57,2021-11-23 15:18:26,13.111,4.418
34,Test,"12.73,4.796",2021-11-23 15:17:48,2021-11-23 15:17:57,12.73,4.796
35,Test,"12.73,4.796",2021-11-23 15:16:37,2021-11-23 15:17:48,12.73,4.796
36,Test,"11.603,4.768",2021-11-23 15:16:21,2021-11-23 15:16:37,11.603,4.768
37,Test,"13.277,4.54",2021-11-23 15:16:13,2021-11-23 15:16:21,13.277,4.54
38,Test,"10.037,16.711",2021-11-23 10:48:31,2021-11-23 10:48:45,10.037,16.711
39,Test,"11.342,16.492",2021-11-23 10:48:14,2021-11-23 10:48:26,11.342,16.492
40,Test,"10.271,17.052",2021-11-23 10:48:07,2021-11-23 10:48:14,10.271,17.052
41,Test,"9.279,17.355",2021-11-23 10:47:29,2021-11-23 10:48:07,9.279,17.355
42,Test,"6.444,10.156",2021-11-22 16:38:15,2021-11-22 16:38:29,6.444,10.156
43,Test,"6.611,12.379",2021-11-22 16:37:08,2021-11-22 16:37:18,6.611,12.379
44,Test,"10.159,21.14",2021-11-22 16:36:57,2021-11-22 16:37:08,10.159,21.14
45,Test,"6.157,12.511",2021-11-22 16:36:31,2021-11-22 16:36:57,6.157,12.511
46,Test,"9.115,20.871",2021-11-22 16:25:15,2021-11-22 16:25:23,9.115,20.871
47,Test,"6.456,13.308",2021-11-22 16:25:03,2021-11-22 16:25:15,6.456,13.308
48,Test,"8.792,21.867",2021-11-22 16:24:58,2021-11-22 16:25:03,8.792,21.867
49,Test,"5.873,11.296",2021-11-22 16:24:33,2021-11-22 16:24:58,5.873,11.296
76647,fdsds,"7.241,7.678",2021-10-07 12:02:11,2021-10-07 12:08:13,7.241,7.678
76648,fdsds,"10.463,7.237",2021-10-07 12:01:22,2021-10-07 12:02:11,10.463,7.237
76649,fdsds,"7.296,7.093",2021-10-07 11:55:49,2021-10-07 12:01:22,7.296,7.093
76650,fdsds,"10.551,4.856",2021-10-07 11:55:45,2021-10-07 11:55:49,10.551,4.856
76651,fdsds,"7.356,6.028",2021-10-07 11:55:43,2021-10-07 11:55:45,7.356,6.028

In [4]:
df = df.drop(df[~df["Patient"].str.startswith(('G', 'R'))].index) # and then drop those rows
df

,Patient,Location,starttime,endtime,xlocation,ylocation
6,G1221,"5.074,4.901",2021-11-25 10:12:24,2021-11-25 23:00:03,5.074,4.901
7,G1221,"4.199,5.469",2021-11-25 10:11:47,2021-11-25 10:12:24,4.199,5.469
50,G1220,"11.73,12.115",2021-11-18 16:30:30,2021-11-18 16:30:35,11.73,12.115
51,G1220,"12.471,13.238",2021-11-18 16:30:28,2021-11-18 16:30:30,12.471,13.238
52,G1220,"13.255,14.711",2021-11-18 16:30:24,2021-11-18 16:30:28,13.255,14.711
...,...,...,...,...,...,...
76642,G4546,"8.075,10.798",2021-10-07 12:33:21,2021-10-07 12:33:25,8.075,10.798
76643,G4546,"9.378,10.666",2021-10-07 12:33:19,2021-10-07 12:33:21,9.378,10.666
76644,G4546,"10.468,10.915",2021-10-07 12:32:37,2021-10-07 12:33:19,10.468,10.915
76645,G4546,"11,11.866",2021-10-07 12:31:51,2021-10-07 12:32:37,11,11.866
76646,G1524,"11.035,11.949",2021-10-07 12:30:58,2021-10-07 12:31:53,11.035,11.949

In [6]:
df['step_length'] = df['endtime'] - df['starttime'] # add in variable that reports the time at each step between records
print(df[df['step_length'] > pd.Timedelta(2, 'h')]) # list out any where the time iterval is greater than 2 hours for an individual step

      Patient       Location           starttime             endtime  \
6       G1221    5.074,4.901 2021-11-25 10:12:24 2021-11-25 23:00:03
14460   G1043    0.155,9.235 2021-11-10 17:27:26 2021-11-11 09:13:14
21621   R0727  11.006,10.138 2021-11-08 12:39:25 2021-11-17 16:46:36
25122   G0884    6.736,1.797 2021-11-05 10:45:05 2021-11-22 23:00:33
37322   G0751   8.888,16.582 2021-10-28 16:13:49 2021-11-03 14:49:36
59364   R0547   1.414,10.533 2021-10-20 18:19:50 2021-10-21 09:25:39
59850   R0547  10.945,10.034 2021-10-20 15:48:17 2021-10-20 17:54:51
66408   G0568   0.891,10.261 2021-10-18 18:03:58 2021-10-19 09:20:11
66412   G0569    1.27,10.881 2021-10-18 17:17:06 2021-10-19 09:20:03
68219   R0529   8.195,16.929 2021-10-18 12:39:49 2021-11-22 23:00:33
68359   G0547   6.072,16.116 2021-10-18 12:26:40 2021-11-22 23:00:33
69809   G0537     0.51,9.692 2021-10-16 16:07:04 2021-10-18 09:27:57
69811   G0537     0.623,9.61 2021-10-15 16:57:41 2021-10-16 16:07:02
70513   G0516   7.352,17.973 2021-10-15 13:19:36 2021-10-18 13:56:36
71678   G0528  10.226,11.102 2021-10-15 11:18:05 2021-10-15 13:26:36
72013   G0529   0.823,11.086 2021-10-15 07:21:51 2021-10-15 09:25:19
72014   G0529   0.846,10.152 2021-10-14 17:12:45 2021-10-15 07:21:51
72025   G0528   1.085,10.641 2021-10-14 16:42:17 2021-10-15 09:26:33
72111   G0528   11.066,9.913 2021-10-14 13:37:30 2021-10-14 16:41:56
74239   G0522    0.388,9.786 2021-10-13 06:54:59 2021-10-13 09:54:59
74241   G0522    0.335,9.747 2021-10-13 04:09:03 2021-10-13 06:44:24
74243   R0540    0.599,9.551 2021-10-13 01:16:58 2021-10-13 10:22:44
74245   R0522     -0.1,8.769 2021-10-12 18:03:25 2021-10-13 09:42:25
74247   G0542    0.418,9.868 2021-10-12 17:58:37 2021-10-13 09:42:32
74263   G0544    0.443,9.868 2021-10-12 16:58:01 2021-10-13 10:57:55
74268   R0540    0.643,9.828 2021-10-12 16:37:24 2021-10-13 01:16:56
74269   G0522     0.36,9.661 2021-10-12 16:31:24 2021-10-13 04:09:00
74433   G0544   0.629,10.603 2021-10-12 13:05:00 2021-10-12 16:58:01
74648   R0522  -0.051,10.011 2021-10-11 18:06:42 2021-10-12 09:36:58
74649   G0542   0.758,10.841 2021-10-11 18:05:35 2021-10-12 09:36:58
74653   R0540    0.596,9.474 2021-10-11 17:40:25 2021-10-12 10:14:56
74656   G0544    0.701,9.788 2021-10-11 17:40:18 2021-10-12 13:05:00
74657   G0522     0.532,9.71 2021-10-11 17:40:18 2021-10-12 09:38:07
74730   R0540    11.57,7.635 2021-10-11 15:16:21 2021-10-11 17:40:00
74764   G0544  10.859,10.199 2021-10-11 15:08:23 2021-10-11 17:37:51
74945   G0542  11.092,10.188 2021-10-11 14:13:02 2021-10-11 17:37:51
76547   G8784    5.209,6.481 2021-10-08 14:04:45 2021-10-08 16:06:25
76554   G8784    1.171,9.515 2021-10-08 11:19:41 2021-10-08 13:45:47
76563   G8784    0.979,9.208 2021-10-07 13:33:06 2021-10-08 09:55:21

      xlocation ylocation      step_length
6         5.074     4.901  0 days 12:47:39
14460     0.155     9.235  0 days 15:45:48
21621    11.006    10.138  9 days 04:07:11
25122     6.736     1.797 17 days 12:15:28
37322     8.888    16.582  5 days 22:35:47
59364     1.414    10.533  0 days 15:05:49
59850    10.945    10.034  0 days 02:06:34
66408     0.891    10.261  0 days 15:16:13
66412      1.27    10.881  0 days 16:02:57
68219     8.195    16.929 35 days 10:20:44
68359     6.072    16.116 35 days 10:33:53
69809      0.51     9.692  1 days 17:20:53
69811     0.623      9.61  0 days 23:09:21
70513     7.352    17.973  3 days 00:37:00
71678    10.226    11.102  0 days 02:08:31
72013     0.823    11.086  0 days 02:03:28
72014     0.846    10.152  0 days 14:09:06
72025     1.085    10.641  0 days 16:44:16
72111    11.066     9.913  0 days 03:04:26
74239     0.388     9.786  0 days 03:00:00
74241     0.335     9.747  0 days 02:35:21
74243     0.599     9.551  0 days 09:05:46
74245      -0.1     8.769  0 days 15:39:00
74247     0.418     9.868  0 days 15:43:55
74263     0.443     9.868  0 days 17:59:54
74268     0.643     9.828  0 days 08:39:32
74269      0.36     9.661  0 days 11:37:36
74433     0.629    10.603  0 days 03:53:01
74648    -0.051    10.011  0 days 15:30:16
74649     0.758    10.841  0 days 15:31:23
74653     0.596     9.474  0 days 16:34:31
74656     0.701     9.788  0 days 19:24:42
74657     0.532      9.71  0 days 15:57:49
74730     11.57     7.635  0 days 02:23:39
74764    10.859    10.199  0 days 02:29:28
74945    11.092    10.188  0 days 03:24:49
76547     5.209     6.481  0 days 02:01:40
76554     1.171     9.515  0 days 02:26:06
76563     0.979     9.208  0 days 20:22:15

In [8]:
print(df[df['step_length'] < pd.Timedelta(0, 'h')]) # list out any where the time iterval is greater than 2 hours for an individual step

      Patient       Location           starttime             endtime  \
73859   R0503  15.097,14.322 2021-10-13 11:30:38 2021-10-13 11:30:28
73899   G0523   23.004,9.586 2021-10-13 11:17:12 2021-10-13 11:17:04

      xlocation ylocation       step_length
73859    15.097    14.322 -1 days +23:59:50
73899    23.004     9.586 -1 days +23:59:52

In [ ]:
df[df['Patient'] == 'R0651'] # If you want to check data before deletion, use this function to check to see the record that seems to be too long

Empty DataFrame
Columns: [Patient, Location, starttime, endtime, xlocation, ylocation, step_length]
Index: []

In [9]:
df = df.drop(df[df['step_length'] > pd.Timedelta(2, 'h')].index) # remove any individual step records that are more than 2 hours
df = df.drop(df[df['step_length'] < pd.Timedelta(0, 'h')].index) # remove any individual step records that are more than 2 hours

In [10]:
# check the start and end dates of the phase being reported yyyy-mmm-dd
print("Earliest Date: ", df.starttime.min())
print("Latest Date:   ", df.endtime.max())

Earliest Date:  2021-10-07 12:30:58
Latest Date:    2021-11-25 10:12:24

In [11]:
df.nsmallest(10, 'step_length')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
67703,R0531,"19.456,2.922",2021-10-18 14:34:37,2021-10-18 14:34:37,19.456,2.922,0 days 00:00:00
72074,G0510,"25.122,4.893",2021-10-14 14:01:24,2021-10-14 14:01:24,25.122,4.893,0 days 00:00:00
76578,G8784,"8.77,11.268",2021-10-07 12:49:55,2021-10-07 12:49:55,8.77,11.268,0 days 00:00:00
76585,G8784,"11.054,9.839",2021-10-07 12:48:45,2021-10-07 12:48:45,11.054,9.839,0 days 00:00:00
76604,G8784,"12.714,14.078",2021-10-07 12:36:49,2021-10-07 12:36:49,12.714,14.078,0 days 00:00:00
76607,G8784,"13.201,10.347",2021-10-07 12:36:46,2021-10-07 12:36:46,13.201,10.347,0 days 00:00:00
629,G1204,"12.705,13.413",2021-11-18 14:26:44,2021-11-18 14:26:45,12.705,13.413,0 days 00:00:01
793,G1214,"6.241,3.423",2021-11-18 14:02:38,2021-11-18 14:02:39,6.241,3.423,0 days 00:00:01
873,G1208,"7.876,5.803",2021-11-18 13:43:24,2021-11-18 13:43:25,7.876,5.803,0 days 00:00:01
888,G1204,"5.811,8.951",2021-11-18 13:40:08,2021-11-18 13:40:09,5.811,8.951,0 days 00:00:01

In [12]:
df.sort_values(by=['starttime'])

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
76646,G1524,"11.035,11.949",2021-10-07 12:30:58,2021-10-07 12:31:53,11.035,11.949,0 days 00:00:55
76645,G4546,"11,11.866",2021-10-07 12:31:51,2021-10-07 12:32:37,11,11.866,0 days 00:00:46
76644,G4546,"10.468,10.915",2021-10-07 12:32:37,2021-10-07 12:33:19,10.468,10.915,0 days 00:00:42
76643,G4546,"9.378,10.666",2021-10-07 12:33:19,2021-10-07 12:33:21,9.378,10.666,0 days 00:00:02
76642,G4546,"8.075,10.798",2021-10-07 12:33:21,2021-10-07 12:33:25,8.075,10.798,0 days 00:00:04
...,...,...,...,...,...,...,...
53,G1220,"12.89,15.86",2021-11-18 16:28:03,2021-11-18 16:30:24,12.89,15.86,0 days 00:02:21
52,G1220,"13.255,14.711",2021-11-18 16:30:24,2021-11-18 16:30:28,13.255,14.711,0 days 00:00:04
51,G1220,"12.471,13.238",2021-11-18 16:30:28,2021-11-18 16:30:30,12.471,13.238,0 days 00:00:02
50,G1220,"11.73,12.115",2021-11-18 16:30:30,2021-11-18 16:30:35,11.73,12.115,0 days 00:00:05
7,G1221,"4.199,5.469",2021-11-25 10:11:47,2021-11-25 10:12:24,4.199,5.469,0 days 00:00:37

In [13]:
df.dtypes # list out the updated column names and data types

Patient                 object
Location                object
starttime       datetime64[ns]
endtime         datetime64[ns]
xlocation               object
ylocation               object
step_length    timedelta64[ns]
dtype: object

## Create a new dataframe to group each patient id

The code belows gets the earliest and latest times from a patient allowing the total journey time to be tracked.

In [14]:
dfgrouped = df.groupby('Patient', as_index = False).agg(
    {'starttime': ['min'], 'endtime': ['max'], 'xlocation': ['first'], 'ylocation': ['first']})
dfgrouped

     Patient           starttime             endtime xlocation ylocation
                             min                 max     first     first
0      G0132 2021-11-08 12:16:23 2021-11-08 13:32:28    10.862     7.572
1      G0167 2021-11-11 13:26:24 2021-11-11 14:29:53    11.077     7.427
2      G0501 2021-10-11 10:36:54 2021-10-11 12:03:44    11.435    11.725
3      G0502 2021-10-11 10:53:59 2021-10-11 12:17:13     11.41    11.762
4      G0503 2021-10-11 11:20:09 2021-10-11 13:04:09    10.594     9.785
...      ...                 ...                 ...       ...       ...
1054   R0865 2021-11-18 13:34:55 2021-11-18 14:25:30    10.788     7.366
1055   R0866 2021-11-18 14:03:49 2021-11-18 14:42:49    11.752     12.25
1056   R0867 2021-11-18 14:37:17 2021-11-18 15:06:32     10.78     7.532
1057   R0868 2021-11-18 14:39:07 2021-11-18 15:35:06    11.253    12.273
1058   R1089 2021-11-12 11:39:29 2021-11-12 12:28:19    11.057     9.661

[1059 rows x 5 columns]

The code below changes column headers and continues to format and clean the data for subsequent analysis.

In [15]:
flat_cols = []
for i in dfgrouped.columns:
    flat_cols.append(i[0]) # take the first element of the column heading only (ie ignore min, max, first)
dfgrouped.columns = flat_cols

Add in length of journey to each grouped patient id

In [16]:
dfgrouped['visit_length'] = dfgrouped['endtime'] - dfgrouped['starttime']

In [17]:
dfgrouped

,Patient,starttime,endtime,xlocation,ylocation,visit_length
0,G0132,2021-11-08 12:16:23,2021-11-08 13:32:28,10.862,7.572,0 days 01:16:05
1,G0167,2021-11-11 13:26:24,2021-11-11 14:29:53,11.077,7.427,0 days 01:03:29
2,G0501,2021-10-11 10:36:54,2021-10-11 12:03:44,11.435,11.725,0 days 01:26:50
3,G0502,2021-10-11 10:53:59,2021-10-11 12:17:13,11.41,11.762,0 days 01:23:14
4,G0503,2021-10-11 11:20:09,2021-10-11 13:04:09,10.594,9.785,0 days 01:44:00
...,...,...,...,...,...,...
1054,R0865,2021-11-18 13:34:55,2021-11-18 14:25:30,10.788,7.366,0 days 00:50:35
1055,R0866,2021-11-18 14:03:49,2021-11-18 14:42:49,11.752,12.25,0 days 00:39:00
1056,R0867,2021-11-18 14:37:17,2021-11-18 15:06:32,10.78,7.532,0 days 00:29:15
1057,R0868,2021-11-18 14:39:07,2021-11-18 15:35:06,11.253,12.273,0 days 00:55:59
1058,R1089,2021-11-12 11:39:29,2021-11-12 12:28:19,11.057,9.661,0 days 00:48:50

# Delete Outlier Patient Journeys
Check to see if there are any groups of patient records that are over 1 day in length and then remove them from data frame. Assumption here is that if tag timings are greater than 24 hours it is a tag that has been aborted, lost or forgotton about. NOTE: this will remove any records where the same Patient ID has been used twice.

In [18]:
print(dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(1, 'd')]) # list out the ones to be deleted

    Patient           starttime             endtime xlocation ylocation  \
21    G0522 2021-10-11 14:20:48 2021-10-13 11:02:55    10.849     12.25
35    G0537 2021-10-15 14:19:47 2021-10-18 10:14:28    10.124     7.626
40    G0542 2021-10-11 11:44:35 2021-10-13 11:06:52    10.864    12.081
41    G0543 2021-10-11 12:10:08 2021-10-15 13:39:47    10.992     7.316
42    G0544 2021-10-11 13:51:50 2021-10-13 11:07:27    10.888    11.985
247   G0751 2021-10-28 14:33:27 2021-11-03 14:50:18    11.353      7.63
699   G8784 2021-10-07 12:36:20 2021-10-08 16:06:35     1.468    10.702
720   R0522 2021-10-11 14:24:48 2021-10-13 11:01:45    10.876    12.053
738   R0540 2021-10-11 14:09:03 2021-10-13 11:06:43        11    11.946

       visit_length
21  1 days 20:42:07
35  2 days 19:54:41
40  1 days 23:22:17
41  4 days 01:29:39
42  1 days 21:15:37
247 6 days 00:16:51
699 1 days 03:30:15
720 1 days 20:36:57
738 1 days 20:57:40

In [19]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(1, 'd')].index) # delete those over 1 day

In [20]:
dfgrouped['visit_length'].max() # check to see what max length of visit is after first cull

Timedelta('0 days 23:24:54')

Check to see if there are any tags that have been left unchecked at end of day - and delete those records from main dataframe. NOTE: could try and delete the readings that are overnight but difficult pattern to identify - since low percentage of results, just delete - think these are tags that are not checked back in properly?

In [21]:
dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(6, 'h')] # check to see how many patient journeys are over 6 hours - probably not valid so delete

,Patient,starttime,endtime,xlocation,ylocation,visit_length
27,G0528,2021-10-14 11:53:11,2021-10-15 11:18:05,10.539,12.21,0 days 23:24:54
28,G0529,2021-10-14 12:23:15,2021-10-15 11:28:34,11.684,9.606,0 days 23:05:19
65,G0568,2021-10-18 15:35:17,2021-10-19 11:14:37,10.811,7.689,0 days 19:39:20
66,G0569,2021-10-18 15:59:55,2021-10-19 10:23:08,11.437,10.122,0 days 18:23:13
523,G1043,2021-11-10 15:40:27,2021-11-11 10:19:36,10.962,10.329,0 days 18:39:09
744,R0547,2021-10-20 13:34:14,2021-10-21 10:08:36,10.761,8.108,0 days 20:34:22

In [22]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['endtime'] - dfgrouped['starttime'] > pd.Timedelta(6, 'h')].index) # delete those over 5 hours

Check to see how many patient journeys are implausibly short - ie under 15 minutes - and delete those.

In [23]:
dfgrouped['visit_length'].min() # check to see what min length of visit is after first cull

Timedelta('0 days 00:00:21')

In [24]:
dfgrouped[dfgrouped['visit_length'] < pd.Timedelta(15, 'm')] # check to see how many patient journeys are under 15 mins - probably not valid so delete

,Patient,starttime,endtime,xlocation,ylocation,visit_length
124,G0627,2021-10-21 13:37:19,2021-10-21 13:41:30,10.991,7.405,0 days 00:04:11
139,G0642,2021-10-29 13:24:31,2021-10-29 13:26:15,30.962,10.092,0 days 00:01:44
265,G0769,2021-10-29 13:24:23,2021-10-29 13:26:09,11.007,11.905,0 days 00:01:46
303,G0807,2021-10-26 12:25:15,2021-10-26 12:29:41,8.988,8.015,0 days 00:04:26
380,G0884,2021-11-05 10:31:37,2021-11-05 10:45:05,7.806,1.769,0 days 00:13:28
382,G0886,2021-11-05 10:45:33,2021-11-05 10:45:55,7.085,1.698,0 days 00:00:22
397,G0901,2021-11-05 13:48:11,2021-11-05 13:48:48,10.733,7.317,0 days 00:00:37
471,G0985,2021-11-09 15:49:23,2021-11-09 15:49:58,11.058,5.918,0 days 00:00:35
503,G1022,2021-11-10 14:02:34,2021-11-10 14:14:53,8.196,7.408,0 days 00:12:19
696,G1221,2021-11-25 10:11:47,2021-11-25 10:12:24,4.199,5.469,0 days 00:00:37
697,G1524,2021-10-07 12:30:58,2021-10-07 12:31:53,11.035,11.949,0 days 00:00:55
698,G4546,2021-10-07 12:31:51,2021-10-07 12:35:08,10.509,10.806,0 days 00:03:17
816,R0619,2021-10-27 13:50:42,2021-10-27 13:56:19,10.803,8.255,0 days 00:05:37
927,R0733,2021-11-03 14:44:48,2021-11-03 14:46:45,11.048,6.025,0 days 00:01:57
1017,R0828,2021-11-16 10:15:05,2021-11-16 10:15:26,10.613,5.916,0 days 00:00:21
1033,R0844,2021-11-16 15:32:01,2021-11-16 15:41:40,10.82,4.119,0 days 00:09:39

In [25]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['endtime'] - dfgrouped['starttime'] < pd.Timedelta(15, 'm')].index) # delete those under 15 min

In [26]:
dfgrouped

,Patient,starttime,endtime,xlocation,ylocation,visit_length
0,G0132,2021-11-08 12:16:23,2021-11-08 13:32:28,10.862,7.572,0 days 01:16:05
1,G0167,2021-11-11 13:26:24,2021-11-11 14:29:53,11.077,7.427,0 days 01:03:29
2,G0501,2021-10-11 10:36:54,2021-10-11 12:03:44,11.435,11.725,0 days 01:26:50
3,G0502,2021-10-11 10:53:59,2021-10-11 12:17:13,11.41,11.762,0 days 01:23:14
4,G0503,2021-10-11 11:20:09,2021-10-11 13:04:09,10.594,9.785,0 days 01:44:00
...,...,...,...,...,...,...
1054,R0865,2021-11-18 13:34:55,2021-11-18 14:25:30,10.788,7.366,0 days 00:50:35
1055,R0866,2021-11-18 14:03:49,2021-11-18 14:42:49,11.752,12.25,0 days 00:39:00
1056,R0867,2021-11-18 14:37:17,2021-11-18 15:06:32,10.78,7.532,0 days 00:29:15
1057,R0868,2021-11-18 14:39:07,2021-11-18 15:35:06,11.253,12.273,0 days 00:55:59
1058,R1089,2021-11-12 11:39:29,2021-11-12 12:28:19,11.057,9.661,0 days 00:48:50

In [27]:
# make a copy of records (df3) from df that have an equivalent Patient id in dfgrouped
df3 = df[df['Patient'].isin(dfgrouped['Patient'])]  
print('start record count: ', df.Patient.count())
print('clean record count: ', df3.Patient.count())

start record count:  76556
clean record count:  74118

# Export back to clean csv
Assumes user will then move to appropriate "clean data" folder so just using generic output.csv filename.

In [28]:
df3.to_csv('{}_input.csv'.format(phase), index=False) # note use subset of records in df3

To end, print out some patient journey stats for info!

In [29]:
dfgrouped['visit_length'].describe()

count                         1028
mean     0 days 01:17:42.882295719
std      0 days 00:26:01.381706145
min                0 days 00:15:24
25%         0 days 01:00:28.500000
50%         0 days 01:14:11.500000
75%         0 days 01:31:20.500000
max                0 days 05:45:35
Name: visit_length, dtype: object

In [30]:
# check the start and end dates of the phase being reported yyyy-mmm-dd
print("Earliest Date: ", dfgrouped.starttime.min())
print("Latest Date:   ", dfgrouped.endtime.max())

Earliest Date:  2021-10-11 10:36:54
Latest Date:    2021-11-18 16:30:35

End