<a href="https://colab.research.google.com/github/djdunc/hercules/blob/main/data_import/patient_viewer_seconds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import datetime as dt

phase = 'P1' # edit which Phase you are analysing - this is used in graph and file generation
patient = 'G0132'

df = pd.read_csv('{}_input.csv'.format(phase))
df # check what column headings in file

df[df['Patient'] == patient].head()

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
0,G0132,"10.805,11.99",2021-11-08 12:16:23,2021-11-08 12:17:26,10.805,11.990,0 days 00:01:03
1,G0132,"9.721,11.419",2021-11-08 12:17:26,2021-11-08 12:17:52,9.721,11.419,0 days 00:00:26
2,G0132,"8.768,11.076",2021-11-08 12:17:52,2021-11-08 12:17:55,8.768,11.076,0 days 00:00:03
3,G0132,"7.41,9.57",2021-11-08 12:17:55,2021-11-08 12:17:57,7.410,9.570,0 days 00:00:02
4,G0132,"6.72,7.667",2021-11-08 12:17:57,2021-11-08 12:18:15,6.720,7.667,0 days 00:00:18

In [20]:
df['starttime'] = pd.to_datetime(df['starttime'], dayfirst=True) # datetime in YYYY-MM-DD HH:MM:SS format
df['endtime'] = pd.to_datetime(df['endtime'], dayfirst=True)

df['step_length_sec'] = (df['endtime'] - df['starttime']).astype('timedelta64[s]') 
df[df['Patient'] == patient]

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
0,G0132,"10.805,11.99",2021-11-08 12:16:23,2021-11-08 12:17:26,10.805,11.990,0 days 00:01:03,63.0
1,G0132,"9.721,11.419",2021-11-08 12:17:26,2021-11-08 12:17:52,9.721,11.419,0 days 00:00:26,26.0
2,G0132,"8.768,11.076",2021-11-08 12:17:52,2021-11-08 12:17:55,8.768,11.076,0 days 00:00:03,3.0
3,G0132,"7.41,9.57",2021-11-08 12:17:55,2021-11-08 12:17:57,7.410,9.570,0 days 00:00:02,2.0
4,G0132,"6.72,7.667",2021-11-08 12:17:57,2021-11-08 12:18:15,6.720,7.667,0 days 00:00:18,18.0
5,G0132,"7.197,6.758",2021-11-08 12:18:15,2021-11-08 12:24:23,7.197,6.758,0 days 00:06:08,368.0
6,G0132,"6.112,6.86",2021-11-08 12:24:23,2021-11-08 12:32:37,6.112,6.860,0 days 00:08:14,494.0
7,G0132,"7.327,6.722",2021-11-08 12:32:37,2021-11-08 12:32:39,7.327,6.722,0 days 00:00:02,2.0
8,G0132,"7.74,4.612",2021-11-08 12:32:39,2021-11-08 12:32:41,7.740,4.612,0 days 00:00:02,2.0
9,G0132,"6.567,3.426",2021-11-08 12:32:41,2021-11-08 12:32:43,6.567,3.426,0 days 00:00:02,2.0
10,G0132,"4.999,3.103",2021-11-08 12:32:43,2021-11-08 12:32:45,4.999,3.103,0 days 00:00:02,2.0
11,G0132,"3.761,3.623",2021-11-08 12:32:45,2021-11-08 12:32:49,3.761,3.623,0 days 00:00:04,4.0
12,G0132,"4.544,4.435",2021-11-08 12:32:49,2021-11-08 12:37:13,4.544,4.435,0 days 00:04:24,264.0
13,G0132,"3.269,3.584",2021-11-08 12:37:13,2021-11-08 12:37:15,3.269,3.584,0 days 00:00:02,2.0
14,G0132,"3.522,2.048",2021-11-08 12:37:15,2021-11-08 12:38:06,3.522,2.048,0 days 00:00:51,51.0
15,G0132,"3.965,1.111",2021-11-08 12:38:06,2021-11-08 12:54:10,3.965,1.111,0 days 00:16:04,964.0
16,G0132,"4.715,1.944",2021-11-08 12:54:10,2021-11-08 12:54:54,4.715,1.944,0 days 00:00:44,44.0
17,G0132,"6.017,2.475",2021-11-08 12:54:54,2021-11-08 12:55:09,6.017,2.475,0 days 00:00:15,15.0
18,G0132,"18.883,2.251",2021-11-08 12:55:09,2021-11-08 12:55:16,18.883,2.251,0 days 00:00:07,7.0
19,G0132,"18.025,3.442",2021-11-08 12:55:16,2021-11-08 12:55:19,18.025,3.442,0 days 00:00:03,3.0
20,G0132,"22.705,9.647",2021-11-08 12:55:19,2021-11-08 12:55:23,22.705,9.647,0 days 00:00:04,4.0
21,G0132,"21.64,9.941",2021-11-08 12:55:23,2021-11-08 12:55:32,21.640,9.941,0 days 00:00:09,9.0
22,G0132,"22.401,8.524",2021-11-08 12:55:32,2021-11-08 12:55:39,22.401,8.524,0 days 00:00:07,7.0
23,G0132,"22.282,7.507",2021-11-08 12:55:39,2021-11-08 12:55:42,22.282,7.507,0 days 00:00:03,3.0
24,G0132,"21.526,6.403",2021-11-08 12:55:42,2021-11-08 12:55:44,21.526,6.403,0 days 00:00:02,2.0
25,G0132,"20.224,5.818",2021-11-08 12:55:44,2021-11-08 12:55:48,20.224,5.818,0 days 00:00:04,4.0
26,G0132,"18.637,5.499",2021-11-08 12:55:48,2021-11-08 12:57:07,18.637,5.499,0 days 00:01:19,79.0
27,G0132,"18.275,4.569",2021-11-08 12:57:07,2021-11-08 12:59:57,18.275,4.569,0 days 00:02:50,170.0
28,G0132,"18.098,5.837",2021-11-08 12:59:57,2021-11-08 13:00:10,18.098,5.837,0 days 00:00:13,13.0
29,G0132,"18.291,4.712",2021-11-08 13:00:10,2021-11-08 13:09:47,18.291,4.712,0 days 00:09:37,577.0
30,G0132,"17.913,5.988",2021-11-08 13:09:47,2021-11-08 13:09:49,17.913,5.988,0 days 00:00:02,2.0
31,G0132,"16.837,6.096",2021-11-08 13:09:49,2021-11-08 13:09:51,16.837,6.096,0 days 00:00:02,2.0
32,G0132,"15.557,5.417",2021-11-08 13:09:51,2021-11-08 13:21:57,15.557,5.417,0 days 00:12:06,726.0
33,G0132,"13.966,5.565",2021-11-08 13:21:57,2021-11-08 13:22:06,13.966,5.565,0 days 00:00:09,9.0
34,G0132,"14.355,4.45",2021-11-08 13:22:06,2021-11-08 13:24:55,14.355,4.450,0 days 00:02:49,169.0
35,G0132,"14.245,5.55",2021-11-08 13:24:55,2021-11-08 13:24:58,14.245,5.550,0 days 00:00:03,3.0
36,G0132,"14.278,7.005",2021-11-08 13:24:58,2021-11-08 13:25:02,14.278,7.005,0 days 00:00:04,4.0
37,G0132,"14.24,8.043",2021-11-08 13:25:02,2021-11-08 13:30:05,14.240,8.043,0 days 00:05:03,303.0
38,G0132,"15.427,10.001",2021-11-08 13:30:05,2021-11-08 13:30:12,15.427,10.001,0 days 00:00:07,7.0
39,G0132,"15.475,8.875",2021-11-08 13:30:12,2021-11-08 13:30:20,15.475,8.875,0 days 00:00:08,8.0
40,G0132,"15.479,9.932",2021-11-08 13:30:20,2021-11-08 13:30:24,15.479,9.932,0 days 00:00:04,4.0
41,G0132,"14.727,8.399",2021-11-08 13:30:24,2021-11-08 13:31:19,14.727,8.399,0 days 00:00:55,55.0
42,G0132,"14.431,7.406",2021-11-08 13:31:19,2021-11-08 13:31:47,14.431,7.406,0 days 00:00:28,28.0
43,G0132,"14.006,8.417",2021-11-08 13:31:47,2021-11-08 13:31:57,14.006,8.417,0 days 00:00:10,10.0
44,G0132,"12.204,7.134",2021-11-08 13:31:57,2021-11-08 13:31:59,12.204,7.134,0 days 00:00:02,2.0
45,G0132,"10.93,7.304",2021-11-08 13:31:59,2021-11-08 13:32:09,10.930,7.304,0 days 00:00:10,10.0
46,G0132,"9.918,7.166",2021-11-08 13:32:09,2021-11-08 13:32:24,9.918,7.166,0 days 00:00:15,15.0
47,G0132,"10.862,7.572",2021-11-08 13:32:24,2021-11-08 13:32:28,10.862,7.572,0 days 00:00:04,4.0