<a href="https://colab.research.google.com/github/djdunc/hercules/blob/main/data_import/patient_viewer_seconds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import datetime as dt

phase = 'P2' # edit which Phase you are analysing - this is used in graph and file generation
patient = 'G1839'

df = pd.read_csv('{}_input.csv'.format(phase))
df # check what column headings in file

df[df['Patient'] == patient].head()

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
52372,G1839,"3.959,4.489",2022-01-26 11:45:00,2022-01-26 11:47:00,3.959,4.489,0 days 00:02:00
52373,G1839,"6.41,3.361",2022-01-26 11:47:00,2022-01-26 11:47:00,6.410,3.361,0 days 00:00:00
52374,G1839,"7.583,3.645",2022-01-26 11:47:00,2022-01-26 11:48:00,7.583,3.645,0 days 00:01:00
52375,G1839,"9.216,3.754",2022-01-26 11:48:00,2022-01-26 11:48:00,9.216,3.754,0 days 00:00:00
52376,G1839,"10.286,3.063",2022-01-26 11:48:00,2022-01-26 11:48:00,10.286,3.063,0 days 00:00:00

In [2]:
df['starttime'] = pd.to_datetime(df['starttime'], dayfirst=True) # datetime in YYYY-MM-DD HH:MM:SS format
df['endtime'] = pd.to_datetime(df['endtime'], dayfirst=True)

df['step_length_sec'] = (df['endtime'] - df['starttime']).astype('timedelta64[s]') 
#df[df['Patient'] == patient] 
df

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
0,G1221,"4.511,4.699",2021-11-30 10:10:00,2021-11-30 10:10:00,4.511,4.699,0 days 00:00:00,0.0
1,G1221,"5.639,5.397",2021-11-30 10:10:00,2021-11-30 10:10:00,5.639,5.397,0 days 00:00:00,0.0
2,G1221,"4.77,4.893",2021-11-30 10:10:00,2021-11-30 10:10:00,4.770,4.893,0 days 00:00:00,0.0
3,G1221,"5.639,5.397",2021-11-30 10:10:00,2021-11-30 10:10:00,5.639,5.397,0 days 00:00:00,0.0
4,G1221,"4.77,4.885",2021-11-30 10:10:00,2021-11-30 10:10:00,4.770,4.885,0 days 00:00:00,0.0
...,...,...,...,...,...,...,...,...
104677,R4000,"6.951,5.072",2021-12-20 12:05:00,2021-12-20 12:06:00,6.951,5.072,0 days 00:01:00,60.0
104678,R4000,"6.347,5.889",2021-12-20 12:06:00,2021-12-20 12:06:00,6.347,5.889,0 days 00:00:00,0.0
104679,R4000,"6.977,5.084",2021-12-20 12:06:00,2021-12-20 12:06:00,6.977,5.084,0 days 00:00:00,0.0
104680,R4000,"6.347,5.889",2021-12-20 12:06:00,2021-12-20 12:06:00,6.347,5.889,0 days 00:00:00,0.0
104681,R4000,"6.888,5.105",2021-12-20 12:06:00,2021-12-20 12:06:00,6.888,5.105,0 days 00:00:00,0.0

In [18]:
# save all the data for one patient id to csv
patient = 'G1839'
journey = df[df['Patient'] == patient]
print(journey.step_length_sec.sum())
journey.to_csv('{}_journey.csv'.format(patient), index=False)

3900.0

In [19]:
journey

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
52372,G1839,"3.959,4.489",2022-01-26 11:45:00,2022-01-26 11:47:00,3.959,4.489,0 days 00:02:00,120.0
52373,G1839,"6.41,3.361",2022-01-26 11:47:00,2022-01-26 11:47:00,6.410,3.361,0 days 00:00:00,0.0
52374,G1839,"7.583,3.645",2022-01-26 11:47:00,2022-01-26 11:48:00,7.583,3.645,0 days 00:01:00,60.0
52375,G1839,"9.216,3.754",2022-01-26 11:48:00,2022-01-26 11:48:00,9.216,3.754,0 days 00:00:00,0.0
52376,G1839,"10.286,3.063",2022-01-26 11:48:00,2022-01-26 11:48:00,10.286,3.063,0 days 00:00:00,0.0
...,...,...,...,...,...,...,...,...
52446,G1839,"7.19,3.395",2022-01-26 12:49:00,2022-01-26 12:49:00,7.190,3.395,0 days 00:00:00,0.0
52447,G1839,"5.32,3.395",2022-01-26 12:49:00,2022-01-26 12:49:00,5.320,3.395,0 days 00:00:00,0.0
52448,G1839,"3.992,3.274",2022-01-26 12:49:00,2022-01-26 12:49:00,3.992,3.274,0 days 00:00:00,0.0
52449,G1839,"2.886,3.41",2022-01-26 12:49:00,2022-01-26 12:50:00,2.886,3.410,0 days 00:01:00,60.0
52450,G1839,"3.959,4.489",2022-01-26 12:50:00,2022-01-26 12:50:00,3.959,4.489,0 days 00:00:00,0.0

In [20]:
# remove any 0 value time steps then save
patient = 'G1839'
journey = df[df['Patient'] == patient]
print(journey.step_length_sec.sum())
journey.drop(journey.index[journey['step_length_sec'] == 0], inplace = True)
journey.to_csv('{}_journey_no0.csv'.format(patient), index=False)

3900.0

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [21]:
journey

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
52372,G1839,"3.959,4.489",2022-01-26 11:45:00,2022-01-26 11:47:00,3.959,4.489,0 days 00:02:00,120.0
52374,G1839,"7.583,3.645",2022-01-26 11:47:00,2022-01-26 11:48:00,7.583,3.645,0 days 00:01:00,60.0
52378,G1839,"11.514,5.566",2022-01-26 11:48:00,2022-01-26 11:49:00,11.514,5.566,0 days 00:01:00,60.0
52380,G1839,"11.514,5.566",2022-01-26 11:49:00,2022-01-26 11:51:00,11.514,5.566,0 days 00:02:00,120.0
52386,G1839,"17.23,5.59",2022-01-26 11:51:00,2022-01-26 11:52:00,17.230,5.590,0 days 00:01:00,60.0
52387,G1839,"16.596,6.046",2022-01-26 11:52:00,2022-01-26 11:54:00,16.596,6.046,0 days 00:02:00,120.0
52388,G1839,"17.361,5.879",2022-01-26 11:54:00,2022-01-26 11:55:00,17.361,5.879,0 days 00:01:00,60.0
52393,G1839,"16.596,6.046",2022-01-26 11:55:00,2022-01-26 11:56:00,16.596,6.046,0 days 00:01:00,60.0
52394,G1839,"16.594,4.286",2022-01-26 11:56:00,2022-01-26 11:57:00,16.594,4.286,0 days 00:01:00,60.0
52395,G1839,"16.974,5.704",2022-01-26 11:57:00,2022-01-26 11:58:00,16.974,5.704,0 days 00:01:00,60.0
52396,G1839,"16.596,6.046",2022-01-26 11:58:00,2022-01-26 12:00:00,16.596,6.046,0 days 00:02:00,120.0
52397,G1839,"17.592,5.56",2022-01-26 12:00:00,2022-01-26 12:01:00,17.592,5.560,0 days 00:01:00,60.0
52401,G1839,"17.717,5.963",2022-01-26 12:01:00,2022-01-26 12:02:00,17.717,5.963,0 days 00:01:00,60.0
52402,G1839,"16.596,6.046",2022-01-26 12:02:00,2022-01-26 12:04:00,16.596,6.046,0 days 00:02:00,120.0
52405,G1839,"17.408,5.816",2022-01-26 12:04:00,2022-01-26 12:05:00,17.408,5.816,0 days 00:01:00,60.0
52406,G1839,"16.596,6.046",2022-01-26 12:05:00,2022-01-26 12:09:00,16.596,6.046,0 days 00:04:00,240.0
52407,G1839,"17.376,5.798",2022-01-26 12:09:00,2022-01-26 12:13:00,17.376,5.798,0 days 00:04:00,240.0
52413,G1839,"20.196,8.757",2022-01-26 12:13:00,2022-01-26 12:15:00,20.196,8.757,0 days 00:02:00,120.0
52415,G1839,"20.196,10.157",2022-01-26 12:15:00,2022-01-26 12:16:00,20.196,10.157,0 days 00:01:00,60.0
52417,G1839,"20.196,8.757",2022-01-26 12:16:00,2022-01-26 12:17:00,20.196,8.757,0 days 00:01:00,60.0
52419,G1839,"20.196,8.757",2022-01-26 12:17:00,2022-01-26 12:32:00,20.196,8.757,0 days 00:15:00,900.0
52423,G1839,"16.124,11.704",2022-01-26 12:32:00,2022-01-26 12:33:00,16.124,11.704,0 days 00:01:00,60.0
52424,G1839,"13.977,12.826",2022-01-26 12:33:00,2022-01-26 12:34:00,13.977,12.826,0 days 00:01:00,60.0
52426,G1839,"13.977,12.826",2022-01-26 12:34:00,2022-01-26 12:37:00,13.977,12.826,0 days 00:03:00,180.0
52428,G1839,"13.977,12.826",2022-01-26 12:37:00,2022-01-26 12:40:00,13.977,12.826,0 days 00:03:00,180.0
52430,G1839,"13.977,12.826",2022-01-26 12:40:00,2022-01-26 12:42:00,13.977,12.826,0 days 00:02:00,120.0
52432,G1839,"13.977,12.826",2022-01-26 12:42:00,2022-01-26 12:43:00,13.977,12.826,0 days 00:01:00,60.0
52435,G1839,"11.98,16.544",2022-01-26 12:43:00,2022-01-26 12:49:00,11.980,16.544,0 days 00:06:00,360.0
52449,G1839,"2.886,3.41",2022-01-26 12:49:00,2022-01-26 12:50:00,2.886,3.410,0 days 00:01:00,60.0

In [ ]:
df.nlargest(10, 'xlocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
71636,R0821,"34.004,17.487",2021-11-15 15:17:52,2021-11-15 15:27:41,34.004,17.487,0 days 00:09:49,589.0
70882,R0811,"33.88,18.133",2021-11-15 12:46:54,2021-11-15 12:48:07,33.880,18.133,0 days 00:01:13,73.0
70858,R0811,"33.832,18.162",2021-11-15 12:23:51,2021-11-15 12:24:00,33.832,18.162,0 days 00:00:09,9.0
70880,R0811,"33.795,18.202",2021-11-15 12:46:18,2021-11-15 12:46:29,33.795,18.202,0 days 00:00:11,11.0
71634,R0821,"33.792,17.376",2021-11-15 15:17:14,2021-11-15 15:17:41,33.792,17.376,0 days 00:00:27,27.0
70869,R0811,"33.786,18.149",2021-11-15 12:35:35,2021-11-15 12:35:46,33.786,18.149,0 days 00:00:11,11.0
50345,R0528,"33.767,19.527",2021-10-18 11:41:30,2021-10-18 11:41:42,33.767,19.527,0 days 00:00:12,12.0
70871,R0811,"33.76,18.158",2021-11-15 12:35:58,2021-11-15 12:39:57,33.760,18.158,0 days 00:03:59,239.0
70878,R0811,"33.742,18.204",2021-11-15 12:43:34,2021-11-15 12:43:46,33.742,18.204,0 days 00:00:12,12.0
67837,R0759,"33.688,17.176",2021-11-09 15:26:07,2021-11-09 15:26:12,33.688,17.176,0 days 00:00:05,5.0

In [11]:
df.ylocation.min()

0.09

In [10]:
df.nsmallest(10, 'ylocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
12732,G1351,"7.677,0.09",2021-12-06 15:10:00,2021-12-06 15:10:00,7.677,0.090,0 days 00:00:00,0.0
104332,R1305,"6.911,0.516",2022-01-28 13:47:00,2022-01-28 13:47:00,6.911,0.516,0 days 00:00:00,0.0
59070,R0884,"6.468,0.63",2021-12-01 15:38:00,2021-12-01 15:39:00,6.468,0.630,0 days 00:01:00,60.0
6679,G1288,"9.076,0.636",2021-12-03 11:49:00,2021-12-03 11:50:00,9.076,0.636,0 days 00:01:00,60.0
3191,G1247,"6.496,0.651",2021-12-01 11:47:00,2021-12-01 11:47:00,6.496,0.651,0 days 00:00:00,0.0
3189,G1247,"7.034,0.801",2021-12-01 11:39:00,2021-12-01 11:46:00,7.034,0.801,0 days 00:07:00,420.0
63698,R0921,"8.036,0.814",2021-12-06 11:52:00,2021-12-06 11:52:00,8.036,0.814,0 days 00:00:00,0.0
7377,G1296,"6.96,0.855",2021-12-03 12:08:00,2021-12-03 12:20:00,6.960,0.855,0 days 00:12:00,720.0
13105,G1355,"6.945,0.86",2021-12-06 16:27:00,2021-12-06 16:27:00,6.945,0.860,0 days 00:00:00,0.0
12731,G1351,"6.937,0.88",2021-12-06 15:10:00,2021-12-06 15:10:00,6.937,0.880,0 days 00:00:00,0.0

In [9]:
df.nlargest(10, 'ylocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
92639,R1177,"10.959,18.287",2022-01-19 11:55:00,2022-01-19 11:55:00,10.959,18.287,0 days 00:00:00,0.0
6181,G1282,"11,18.284",2021-12-02 15:09:00,2021-12-02 15:09:00,11.000,18.284,0 days 00:00:00,0.0
6177,G1282,"11.422,18.281",2021-12-02 15:08:00,2021-12-02 15:08:00,11.422,18.281,0 days 00:00:00,0.0
38388,G1696,"11.43,18.281",2022-01-17 14:49:00,2022-01-17 14:49:00,11.430,18.281,0 days 00:00:00,0.0
98812,R1220,"12.295,18.281",2022-01-24 16:37:00,2022-01-24 16:37:00,12.295,18.281,0 days 00:00:00,0.0
55776,G4005,"11.566,18.279",2021-12-20 12:03:00,2021-12-20 12:05:00,11.566,18.279,0 days 00:02:00,120.0
92637,R1177,"11.103,18.273",2022-01-19 11:55:00,2022-01-19 11:55:00,11.103,18.273,0 days 00:00:00,0.0
60086,R0893,"11.619,18.271",2021-12-02 11:46:00,2021-12-02 11:46:00,11.619,18.271,0 days 00:00:00,0.0
65166,R0937,"11.609,18.263",2021-12-07 11:56:00,2021-12-07 11:56:00,11.609,18.263,0 days 00:00:00,0.0
70984,R0978,"11.724,18.263",2021-12-09 15:57:00,2021-12-09 15:57:00,11.724,18.263,0 days 00:00:00,0.0

In [12]:
df.to_csv('{}_input_with_sec.csv'.format(phase), index=False)