<a href="https://colab.research.google.com/github/djdunc/hercules/blob/main/data_import/patient_viewer_seconds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import datetime as dt

phase = 'P1' # edit which Phase you are analysing - this is used in graph and file generation
patient = 'G0132'

df = pd.read_csv('{}_input.csv'.format(phase))
df # check what column headings in file

df[df['Patient'] == patient].head()

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
0,G0132,"10.805,11.99",2021-11-08 12:16:23,2021-11-08 12:17:26,10.805,11.990,0 days 00:01:03
1,G0132,"9.721,11.419",2021-11-08 12:17:26,2021-11-08 12:17:52,9.721,11.419,0 days 00:00:26
2,G0132,"8.768,11.076",2021-11-08 12:17:52,2021-11-08 12:17:55,8.768,11.076,0 days 00:00:03
3,G0132,"7.41,9.57",2021-11-08 12:17:55,2021-11-08 12:17:57,7.410,9.570,0 days 00:00:02
4,G0132,"6.72,7.667",2021-11-08 12:17:57,2021-11-08 12:18:15,6.720,7.667,0 days 00:00:18

In [22]:
df['starttime'] = pd.to_datetime(df['starttime'], dayfirst=True) # datetime in YYYY-MM-DD HH:MM:SS format
df['endtime'] = pd.to_datetime(df['endtime'], dayfirst=True)

df['step_length_sec'] = (df['endtime'] - df['starttime']).astype('timedelta64[s]') 
#df[df['Patient'] == patient] 
df

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
0,G0132,"10.805,11.99",2021-11-08 12:16:23,2021-11-08 12:17:26,10.805,11.990,0 days 00:01:03,63.0
1,G0132,"9.721,11.419",2021-11-08 12:17:26,2021-11-08 12:17:52,9.721,11.419,0 days 00:00:26,26.0
2,G0132,"8.768,11.076",2021-11-08 12:17:52,2021-11-08 12:17:55,8.768,11.076,0 days 00:00:03,3.0
3,G0132,"7.41,9.57",2021-11-08 12:17:55,2021-11-08 12:17:57,7.410,9.570,0 days 00:00:02,2.0
4,G0132,"6.72,7.667",2021-11-08 12:17:57,2021-11-08 12:18:15,6.720,7.667,0 days 00:00:18,18.0
...,...,...,...,...,...,...,...,...
74115,R1089,"13.503,12.677",2021-11-12 12:25:10,2021-11-12 12:25:12,13.503,12.677,0 days 00:00:02,2.0
74116,R1089,"13.897,13.789",2021-11-12 12:25:12,2021-11-12 12:28:08,13.897,13.789,0 days 00:02:56,176.0
74117,R1089,"12.943,12.276",2021-11-12 12:28:08,2021-11-12 12:28:10,12.943,12.276,0 days 00:00:02,2.0
74118,R1089,"12.56,10.272",2021-11-12 12:28:10,2021-11-12 12:28:12,12.560,10.272,0 days 00:00:02,2.0
74119,R1089,"11.057,9.661",2021-11-12 12:28:12,2021-11-12 12:28:19,11.057,9.661,0 days 00:00:07,7.0

In [36]:
df.nlargest(10, 'xlocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
71636,R0821,"34.004,17.487",2021-11-15 15:17:52,2021-11-15 15:27:41,34.004,17.487,0 days 00:09:49,589.0
70882,R0811,"33.88,18.133",2021-11-15 12:46:54,2021-11-15 12:48:07,33.880,18.133,0 days 00:01:13,73.0
70858,R0811,"33.832,18.162",2021-11-15 12:23:51,2021-11-15 12:24:00,33.832,18.162,0 days 00:00:09,9.0
70880,R0811,"33.795,18.202",2021-11-15 12:46:18,2021-11-15 12:46:29,33.795,18.202,0 days 00:00:11,11.0
71634,R0821,"33.792,17.376",2021-11-15 15:17:14,2021-11-15 15:17:41,33.792,17.376,0 days 00:00:27,27.0
70869,R0811,"33.786,18.149",2021-11-15 12:35:35,2021-11-15 12:35:46,33.786,18.149,0 days 00:00:11,11.0
50345,R0528,"33.767,19.527",2021-10-18 11:41:30,2021-10-18 11:41:42,33.767,19.527,0 days 00:00:12,12.0
70871,R0811,"33.76,18.158",2021-11-15 12:35:58,2021-11-15 12:39:57,33.760,18.158,0 days 00:03:59,239.0
70878,R0811,"33.742,18.204",2021-11-15 12:43:34,2021-11-15 12:43:46,33.742,18.204,0 days 00:00:12,12.0
67837,R0759,"33.688,17.176",2021-11-09 15:26:07,2021-11-09 15:26:12,33.688,17.176,0 days 00:00:05,5.0

In [34]:
df.ylocation.min()

-1.398

In [35]:
df.nsmallest(10, 'ylocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
5736,G0566,"5.024,-1.398",2021-10-18 15:39:43,2021-10-18 15:39:58,5.024,-1.398,0 days 00:00:15,15.0
1117,G0510,"4.646,-1.353",2021-10-14 11:52:19,2021-10-14 11:52:23,4.646,-1.353,0 days 00:00:04,4.0
968,G0509,"6.929,-1.176",2021-10-13 15:18:42,2021-10-13 15:18:49,6.929,-1.176,0 days 00:00:07,7.0
5732,G0566,"6.124,-1.093",2021-10-18 15:33:31,2021-10-18 15:33:35,6.124,-1.093,0 days 00:00:04,4.0
1114,G0510,"4.489,-1.067",2021-10-14 11:52:09,2021-10-14 11:52:13,4.489,-1.067,0 days 00:00:04,4.0
5734,G0566,"5.968,-1.031",2021-10-18 15:34:31,2021-10-18 15:35:07,5.968,-1.031,0 days 00:00:36,36.0
3056,G0531,"5.402,-1.025",2021-10-15 10:27:31,2021-10-15 10:28:48,5.402,-1.025,0 days 00:01:17,77.0
5742,G0566,"5.119,-0.999",2021-10-18 15:42:16,2021-10-18 15:42:39,5.119,-0.999,0 days 00:00:23,23.0
3054,G0531,"5.806,-0.937",2021-10-15 10:26:50,2021-10-15 10:27:00,5.806,-0.937,0 days 00:00:10,10.0
412,G0503,"7.753,-0.93",2021-10-11 12:00:02,2021-10-11 12:00:18,7.753,-0.930,0 days 00:00:16,16.0

In [31]:
df.nlargest(10, 'ylocation')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length,step_length_sec
48353,R0506,"18.124,22.589",2021-10-14 11:32:18,2021-10-14 11:32:34,18.124,22.589,0 days 00:00:16,16.0
50345,R0528,"33.767,19.527",2021-10-18 11:41:30,2021-10-18 11:41:42,33.767,19.527,0 days 00:00:12,12.0
49567,R0520,"31.438,19.442",2021-10-11 11:21:47,2021-10-11 11:21:53,31.438,19.442,0 days 00:00:06,6.0
49558,R0520,"31.402,19.4",2021-10-11 11:20:29,2021-10-11 11:20:39,31.402,19.400,0 days 00:00:10,10.0
49560,R0520,"31.315,19.35",2021-10-11 11:20:42,2021-10-11 11:20:46,31.315,19.350,0 days 00:00:04,4.0
50377,R0528,"32.399,19.296",2021-10-18 11:53:50,2021-10-18 11:54:02,32.399,19.296,0 days 00:00:12,12.0
49562,R0520,"31.164,19.282",2021-10-11 11:20:54,2021-10-11 11:21:15,31.164,19.282,0 days 00:00:21,21.0
49583,R0520,"31.327,19.273",2021-10-11 11:25:31,2021-10-11 11:25:40,31.327,19.273,0 days 00:00:09,9.0
49564,R0520,"31.313,19.271",2021-10-11 11:21:21,2021-10-11 11:21:24,31.313,19.271,0 days 00:00:03,3.0
50332,R0528,"33.323,19.143",2021-10-18 11:37:49,2021-10-18 11:39:39,33.323,19.143,0 days 00:01:50,110.0

In [23]:
df.to_csv('{}_input_with_sec.csv'.format(phase), index=False)