# Box Plots for journey times through BX

Import data, group by patient id

## Initialisation

Import dependencies, initialise some variables including loading in data. Files to import are based on filtered Ubisense "all rawdata" downloads. These are stored in the github folder "data" of this repo.

In [ ]:
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import numpy as np
import datetime as dt
import math
import seaborn as sns
import scipy.stats as sps
from scipy import stats

order_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
order_list_noweekend = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

pd.set_option('display.max_rows', 300) # specifies number of rows to show
pd.options.display.float_format = '{:40,.4f}'.format # specifies default number format to 4 decimal places
plt.style.use('ggplot') # specifies that graphs should use ggplot styling

df = pd.read_csv('output-2.csv')

df['starttime'] = pd.to_datetime(df['starttime']) # datetime in YYYY-MM-DD HH:MM:SS format
df['endtime'] = pd.to_datetime(df['endtime'])

df # check what column headings in file

In [ ]:
# check the start and end dates of the phase being reported yyyy-mmm-dd
print("Earliest Date: ", df.starttime.min())
print("Latest Date:   ", df.endtime.max())

## Create a new dataframe to group each patient id

The code belows gets the earliest and latest times from a patient allowing the total journey time to be tracked.

In [ ]:
dfgrouped = df.groupby('Patient', as_index = False).agg(
    {'starttime': ['min'], 'endtime': ['max'], 'xlocation': ['first'], 'ylocation': ['first']})
dfgrouped.head()

The code below changes column headers and continues to format and clean the data for subsequent analysis.

In [ ]:
flat_cols = []
for i in dfgrouped.columns:
    flat_cols.append(i[0]) # take the first element of the column heading only (ie ignore min, max, first)
dfgrouped.columns = flat_cols

Add in length of journey to each grouped patient id

In [ ]:
dfgrouped['visit_length'] = dfgrouped['endtime'] - dfgrouped['starttime']

In [ ]:
print(dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(1, 'd')]) # this should return no results!

In [35]:
dfgrouped['visit_length'].describe()

count                         1028
mean     0 days 01:17:42.882295719
std      0 days 00:26:01.381706145
min                0 days 00:15:24
25%         0 days 01:00:28.500000
50%         0 days 01:14:11.500000
75%         0 days 01:31:20.500000
max                0 days 05:45:35
Name: visit_length, dtype: object

Add in a day of week column value.

In [33]:
dfgrouped['dayofweek'] = dfgrouped['starttime'].dt.day_name()
df_final= dfgrouped.dropna()

In [ ]:
df_final

## Day of the Week Analysis

In [40]:
dayoftheweekmean = df_final.groupby('dayofweek')['visit_length'].mean(numeric_only=False)
dayoftheweekmean = dayoftheweekmean.reindex(index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
dayoftheweekmean

dayofweek
Monday      0 days 01:18:01.418410041
Tuesday     0 days 01:19:33.145539906
Wednesday   0 days 01:20:31.112745098
Thursday    0 days 01:16:39.277777777
Friday      0 days 01:12:57.586206896
Saturday                          NaT
Sunday                            NaT
Name: visit_length, dtype: timedelta64[ns]


## Time of Day Analysis

Afternoon is defined as a journey starting from 13:00 onwards whereas any journey starting prior to 13:00 is defined as starting in the morning.

In [41]:
def ftod(x):
    if (x>13):
        tod = 'afternoon'
    else:
        tod = 'morning'
    return tod

In [42]:
df_final['tod'] = df_final.starttime.dt.hour.map(ftod)

In [43]:
timeofdaymean = df_final.groupby('tod')['visit_length'].mean(numeric_only=False)

In [44]:
timeofdaymean

tod
afternoon   0 days 01:15:39.065573770
morning     0 days 01:18:51.336858006
Name: visit_length, dtype: timedelta64[ns]

## Day of the Week Analysis

In [45]:
df_dayoftheweekmean = pd.DataFrame(data=dayoftheweekmean)

In [46]:
df_dayoftheweekmean

                       visit_length
dayofweek
Monday    0 days 01:18:01.418410041
Tuesday   0 days 01:19:33.145539906
Wednesday 0 days 01:20:31.112745098
Thursday  0 days 01:16:39.277777777
Friday    0 days 01:12:57.586206896
Saturday                        NaT
Sunday                          NaT

In [49]:
Monday_count = df_final['dayofweek'][df_final['dayofweek']=='Monday'].count()
print('Mon ', Monday_count)

Tuesday_count = df_final['dayofweek'][df_final['dayofweek']=='Tuesday'].count()
print('Tue ', Tuesday_count)

Wednesday_count = df_final['dayofweek'][df_final['dayofweek']=='Wednesday'].count()
print('Wed ', Wednesday_count)

Thursday_count = df_final['dayofweek'][df_final['dayofweek']=='Thursday'].count()
print('Thu ', Thursday_count)

Friday_count = df_final['dayofweek'][df_final['dayofweek']=='Friday'].count()
print('Fri ', Friday_count)

Saturday_count = df_final['dayofweek'][df_final['dayofweek']=='Saturday'].count()
print('Sat ', Saturday_count)

Sunday_count = df_final['dayofweek'][df_final['dayofweek']=='Sunday'].count()
print('Sun ', Sunday_count)

Mon  239
Tue  213
Wed  204
Thu  198
Fri  174
Sat  0
Sun  0

In [50]:
weekday_data = {'dayofweek':['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
          'count': [Monday_count , Tuesday_count , Wednesday_count , Thursday_count , Friday_count , Saturday_count , Sunday_count ]}
weekday_df = pd.DataFrame(weekday_data)

## Start of Starting Hour Analysis

Here we look to analyse if there are any differences by the hour at which the patient journey starts.

In [51]:
df_final['hour'] = df_final['starttime'].dt.hour

In [52]:
df_final

,Patient,starttime,endtime,xlocation,ylocation,visit_length,dayofweek,tod,hour
0,G0132,2021-11-08 12:16:23,2021-11-08 13:32:28,10.8050,11.9900,0 days 01:16:05,Monday,morning,12
1,G0167,2021-11-11 13:26:24,2021-11-11 14:29:53,10.9130,7.3610,0 days 01:03:29,Thursday,morning,13
2,G0501,2021-10-11 10:36:54,2021-10-11 12:03:44,11.1820,11.8080,0 days 01:26:50,Monday,morning,10
3,G0502,2021-10-11 10:53:59,2021-10-11 12:17:13,9.7440,11.1950,0 days 01:23:14,Monday,morning,10
4,G0503,2021-10-11 11:20:09,2021-10-11 13:04:09,9.2630,11.2680,0 days 01:44:00,Monday,morning,11
...,...,...,...,...,...,...,...,...,...
1023,R0865,2021-11-18 13:34:55,2021-11-18 14:25:30,12.2420,8.4200,0 days 00:50:35,Thursday,morning,13
1024,R0866,2021-11-18 14:03:49,2021-11-18 14:42:49,11.6590,11.3150,0 days 00:39:00,Thursday,afternoon,14
1025,R0867,2021-11-18 14:37:17,2021-11-18 15:06:32,10.7020,7.9650,0 days 00:29:15,Thursday,afternoon,14
1026,R0868,2021-11-18 14:39:07,2021-11-18 15:35:06,12.0530,10.8660,0 days 00:55:59,Thursday,afternoon,14
1027,R1089,2021-11-12 11:39:29,2021-11-12 12:28:19,10.8990,7.4910,0 days 00:48:50,Friday,morning,11

In [53]:
hourlymean = df_final.groupby('hour')['visit_length'].mean(numeric_only=False)

In [54]:
hourlymean

hour
9              0 days 01:15:02
10   0 days 01:18:01.648854961
11   0 days 01:22:21.080808080
12   0 days 01:20:45.936708860
13   0 days 01:13:39.203539823
14   0 days 01:19:04.030303030
15   0 days 01:10:19.539062500
16             0 days 01:00:18
Name: visit_length, dtype: timedelta64[ns]

In [55]:
df_final.dtypes

Patient                  object
starttime        datetime64[ns]
endtime          datetime64[ns]
xlocation               float64
ylocation               float64
visit_length    timedelta64[ns]
dayofweek                object
tod                      object
hour                      int64
dtype: object

In [57]:
nine_count = df_final['hour'][df_final['hour']==9].count()
print('09:00 ', nine_count)

ten_count = df_final['hour'][df_final['hour']==10].count()
print('10:00 ', ten_count)

print('Eleven')
eleven_count = df_final['hour'][df_final['hour']==11].count()
print(eleven_count)

print('Twelve')
twelve_count = df_final['hour'][df_final['hour']==12].count()
print(twelve_count)

print('One')
one_count = df_final['hour'][df_final['hour']==13].count()
print(one_count)

print('Two')
two_count = df_final['hour'][df_final['hour']==14].count()
print(two_count)

print('Three')
three_count = df_final['hour'][df_final['hour']==15].count()
print(three_count)

print('Four')
four_count = df_final['hour'][df_final['hour']==16].count()
print(four_count)

09:00  10
10:00  262
Eleven
198
Twelve
79
One
113
Two
231
Three
128
Four
7

## Patient Condition Analysis

This analysis begins to compare the journies of patients with either Glaucoma or Medical Retina.

In [ ]:
df_final['condition'] = df_final['Patient'].str[0]

In [ ]:
conditionmean = df_final.groupby('condition')['visit_length'].mean(numeric_only=False)

In [ ]:
conditionmean

In [ ]:
print('Glaucoma')
glaucoma_count = df_final['condition'][df_final['condition']=='G'].count()
print(glaucoma_count)

print('Medical Retinal')
retina_count = df_final['condition'][df_final['condition']=='R'].count()
print(retina_count)

## Converting Visit Length to Minutes

The following code converts the visit length into a more usable data format. The final data is an integer representing the number of minutes that the journey took to complete.

In [ ]:
def get_seconds(time_delta):
    return time_delta.seconds

time_delta_series = df_final['visit_length']

df_final['visit_length_minutes'] = time_delta_series.apply(get_seconds)

In [ ]:
df_final['visit_length_minutes'] = df_final['visit_length_minutes'] / 60

In [ ]:
df_final

## Initial Plots

These are the starting visualisations. Final versions are seen later in the notebook.

In [ ]:
axdayoftheweek = sns.boxplot(x="dayofweek", y="visit_length_minutes", data=df_final)

In [ ]:
axtod = sns.boxplot(x="tod", y="visit_length_minutes", data=df_final)

In [ ]:
axhour = sns.boxplot(x="hour", y="visit_length_minutes", data=df_final)

In [ ]:
axcondition = sns.boxplot(x="condition", y="visit_length_minutes", data=df_final)

## Outlier Removal

There are many odd outliers in this data. This section removes these outliers.

In [ ]:
df_outliers = df_final[(np.abs(stats.zscore(df_final['visit_length_minutes'])) < 3)]
df_outliers.loc[(df_outliers[['visit_length_minutes']] < 10).all(axis=1)]
print(df_outliers.loc[(df_outliers[['visit_length_minutes']] < 10).all(axis=1)].count())

## Removal of 0 Minute Journeys

The section below creates a dataframe where journeys that have a journey time of 0 minutes are removed.

In [ ]:
df_nozero = df_outliers.loc[(df_outliers[['visit_length_minutes']] != 0).all(axis=1)]
df_nozero

## Start of Final Analysis

In [ ]:
mean = df_outliers['visit_length_minutes'].mean()
print(mean)
print(df_nozero['visit_length_minutes'].mean())

## Day of Week Analysis and Plots

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(x="dayofweek", y="visit_length_minutes", data=df_outliers, order = order_list)
svm.set_title('Visit Length in Minutes by Day of the Week')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Day of the Week')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('dayofweek_updated.png', bbox_inches='tight')

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(x="dayofweek", y="visit_length_minutes", data=df_outliers, order = order_list_noweekend)
svm.set_title('Visit Length in Minutes by Day of the Week')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Day of the Week')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('dayofweek_updated_noweekend.png', bbox_inches='tight')

## Time of Day Analysis and Plots

In [ ]:
axtod = sns.boxplot(x="tod", y="visit_length_minutes", data=df_outliers)

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(x="tod", y="visit_length_minutes", data=df_outliers)
svm.set_title('Visit Length in Minutes by Time of Day (Afternoon defined as Start time Occuring after 13:00)')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Time of Day')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('timeofday_updated.png', bbox_inches='tight')

## Condition Analysis and Plots

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(x="condition", y="visit_length_minutes", data=df_outliers)
svm.set_title('Visit Length in Minutes by Condition')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Time of Day')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('condition_updated.png', bbox_inches='tight')

In [ ]:
axcondition = sns.boxplot(x="condition", y="visit_length_minutes", data=df_outliers)

## Starting Hour Analysis and Plots

In [ ]:
axhour = sns.boxplot(x="hour", y="visit_length_minutes", data=df_outliers)

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(x="hour", y="visit_length_minutes", data=df_outliers)
svm.set_title('Visit Length in Minutes by Starting Hour')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Starting Hour')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('hour_updated.png', bbox_inches='tight')

## Summary Statistics of Each Analysis

The section below gets the summary statistics of each analysis done. These are used in the PowerPoint in the Findings folder in the MS Teams.

In [ ]:
dayoftheweekmean = df_outliers.groupby('dayofweek')['visit_length'].mean(numeric_only=False)
dayoftheweekmean = dayoftheweekmean.reindex(index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

In [ ]:
df_outliers['visit_length_minutes'].describe()

In [ ]:
df_final['visit_length_minutes'].describe()

In [ ]:
df_final['visit_length_minutes'].median()

In [ ]:
df_outliers['visit_length'].describe()

In [ ]:
df_final['visit_length'].describe()

In [ ]:
sns.set_style('whitegrid')
sns.set_theme(palette="colorblind")
f,ax = plt.subplots(figsize=(8,5))
svm = sns.boxplot(y="visit_length_minutes", data=df_outliers)
svm.set_title('Overall')
svm.set_ylabel('Visit Length in Minutes')
svm.set_xlabel('Total')
svm.axhline(mean, linestyle = '--', color = 'black', label = 'Overall Mean')
svm.legend(bbox_to_anchor = (0.85, 1), loc = 'upper center')
figure1 = svm.get_figure()
figure1.savefig('tested.png', bbox_inches='tight')

In [ ]:
print('Nine')
nine_count = df_outliers['hour'][df_outliers['hour']==9].count()
print(nine_count)

print('Ten')
ten_count = df_outliers['hour'][df_outliers['hour']==10].count()
print(ten_count)

print('Eleven')
eleven_count = df_outliers['hour'][df_outliers['hour']==11].count()
print(eleven_count)

print('Twelve')
twelve_count = df_outliers['hour'][df_outliers['hour']==12].count()
print(twelve_count)

print('One')
one_count = df_outliers['hour'][df_outliers['hour']==13].count()
print(one_count)

print('Two')
two_count = df_outliers['hour'][df_outliers['hour']==14].count()
print(two_count)

print('Three')
three_count = df_outliers['hour'][df_outliers['hour']==15].count()
print(three_count)

print('Four')
four_count = df_outliers['hour'][df_outliers['hour']==16].count()
print(four_count)

In [ ]:
print('Monday Outlier')
mondayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Monday'].count()
print(mondayoutlier)

print('Tuesday Outlier')
tuesdayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Tuesday'].count()
print(tuesdayoutlier)

print('Wednesday Outlier')
wednesdayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Wednesday'].count()
print(wednesdayoutlier)

print('Thursday Outlier')
thursdayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Thursday'].count()
print(thursdayoutlier)

print('Friday Outlier')
fridayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Friday'].count()
print(fridayoutlier)

print('Saturday Outlier')
saturdayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Saturday'].count()
print(saturdayoutlier)

print('Sunday Outlier')
sundayoutlier = df_outliers['dayofweek'][df_outliers['dayofweek']=='Sunday'].count()
print(sundayoutlier)

In [ ]:
dayoftheweekmean = df_outliers.groupby('dayofweek')['visit_length_minutes'].mean(numeric_only=False)
dayoftheweekmean = dayoftheweekmean.reindex(index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

In [ ]:
dayoftheweekmean

In [ ]:
print('G')
glaucomacount = df_outliers['condition'][df_outliers['condition']=='G'].count()
print(glaucomacount)

print('R')
rcount = df_outliers['condition'][df_outliers['condition']=='R'].count()
print(rcount)

In [ ]:
conditionmean = df_outliers.groupby('condition')['visit_length_minutes'].mean(numeric_only=False)
conditionmean

In [ ]:
print('morning')
morningcount = df_outliers['tod'][df_outliers['tod']=='morning'].count()
print(morningcount)

print('afternoon')
afternooncount = df_outliers['tod'][df_outliers['tod']=='afternoon'].count()
print(afternooncount)

In [ ]:
todmean = df_outliers.groupby('tod')['visit_length_minutes'].mean(numeric_only=False)
todmean

In [ ]:
print('Nine')
nine_count = df_outliers['hour'][df_outliers['hour']==9].count()
print(nine_count)

print('Ten')
ten_count = df_outliers['hour'][df_outliers['hour']==10].count()
print(ten_count)

print('Eleven')
eleven_count = df_outliers['hour'][df_outliers['hour']==11].count()
print(eleven_count)

print('Twelve')
twelve_count = df_outliers['hour'][df_outliers['hour']==12].count()
print(twelve_count)

print('One')
one_count = df_outliers['hour'][df_outliers['hour']==13].count()
print(one_count)

print('Two')
two_count = df_outliers['hour'][df_outliers['hour']==14].count()
print(two_count)

print('Three')
three_count = df_outliers['hour'][df_outliers['hour']==15].count()
print(three_count)

print('Four')
four_count = df_outliers['hour'][df_outliers['hour']==16].count()
print(four_count)

In [ ]:
hourmean = df_outliers.groupby('hour')['visit_length_minutes'].mean(numeric_only=False)
hourmean

In [ ]:
df_outliers.loc[(df_outliers[['visit_length_minutes']] < 10).all(axis=1)]

In [ ]:
df_outliers.loc[(df_outliers[['visit_length_minutes']] < 10).all(axis=1)].count()

In [ ]:
df_outliers.loc[(df_outliers[['visit_length_minutes']] == 0).all(axis=1)].count()

In [ ]:
df_outliers.loc[(df_outliers[['visit_length']]).all(axis=1)].count()

In [ ]:
df_outliers.nsmallest(5, 'visit_length')

In [ ]:
df_outliers.nsmallest(5, 'visit_length_minutes')

In [ ]:
df_outliers.nlargest(5, 'visit_length_minutes')

In [ ]:
df_outliers.nlargest(5, 'visit_length')

In [ ]:
df_final.nlargest(20, 'visit_length')

In [ ]:
df_outliers.nlargest(20, 'visit_length')

## CSV Creation

This creates a CSV of the patient journies which can be used for subsequent analysis (e.g. cluster analysis).

In [ ]:
phase2df = df_outliers[['Patient', 'starttime', 'endtime', 'visit_length', 'dayofweek', 'tod', 'hour', 'condition', 'visit_length_minutes']].copy()
phase2df.to_csv('phase2df.csv', index=False)